---
# Install and configure ElasticSearch

- name: install elasticsearch signing key
  ansible.builtin.apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  become: yes

- name: install elasticsearch repository
  ansible.builtin.apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/1.7/debian stable main'
    state: present
  become: yes

- name: install elasticsearch and dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  loop:
    - openjdk-7-jre-headless
    - elasticsearch
    - curl
    - python-passlib
  become: yes


- name: configure the elasticsearch environment defaults
  ansible.builtin.template:
    src: elasticsearch.j2
    dest: "{{ elasticsearch_defaults_file }}"
    owner: root
    group: root
    mode: 0644
  register: _elasticsearch_env_conf_status
  become: yes

- name: configure elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  register: _elasticsearch_conf_status
  become: yes

- name: configure the elasticsearch logging
  ansible.builtin.template:
    src: logging.yml.j2
    dest: /etc/elasticsearch/logging.yml
    owner: root
    group: root
    mode: 0644
  register: _elasticsearch_log_conf_status
  become: yes

- name: restart elasticsearch if configuration was changed
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
  become: yes
  when: _elasticsearch_env_conf_status.changed or _elasticsearch_conf_status.changed or _elasticsearch_log_conf_status.changed


- name: enable elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    enabled: yes
    state: started
  become: yes
